# Generated by Django 3.1.2 on 2020-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='timestamp',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
