# Generated by Django 3.1.2 on 2020-11-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201116_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='name',
        ),
    ]
